# docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Monta el código local para desarrollo con live-reload
      - ./backend:/app
    env_file:
      - ./backend/c-Users-jojor-OneDrive-Escritorio-chatbot2-backend-.env
    environment:
      # Esta URL apunta al servicio 'db' de Docker Compose con las credenciales correctas
      - DATABASE_URL=postgresql://ingrequerimientos:ingrequerimientos@db:5432/chatbot_db
    depends_on:
      - db # Asegura que la base de datos inicie antes que el backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Expone el puerto 80 de Nginx en el puerto 5173 de tu máquina
    depends_on:
      - backend # Asegura que el backend inicie antes que el frontend

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ingrequerimientos
      - POSTGRES_PASSWORD=ingrequerimientos
      - POSTGRES_DB=chatbot_db
    ports:
      - "5432:5432" # Opcional: para conectar a la BD desde tu máquina

volumes:
  postgres_data:
